services:
  - type: web
    name: chamados-backend
    runtime: python
    buildCommand: "./start.sh"
    startCommand: "gunicorn -b 0.0.0.0:10000 src.main:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: chave_super_secreta
      - key: DB_USERNAME
        value: chamados_user
      - key: DB_PASSWORD
        value: senha_segura
      - key: DB_HOST
        fromDatabase:
          name: chamados-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: chamados-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: chamados-db
          property: database
databases:
  - name: chamados-db
    databaseName: chamados_tecnicos
    user: chamados_user